import {
  Company,
  User,
  CompanyMembership,
  Letter,
  ArchiveDocument,
  Attachment,
  FinancialTransaction,
  Shareholder,
  BoardMeeting,
  Project,
  AuditLog,
  UserDevice,
  BackupRecord,
} from '../types';

export const INITIAL_COMPANIES: Company[] = [
  {
    id: 'comp_sepehr',
    legal_name: 'شرکت داده‌پردازی و فناوری اطلاعات نوین سپهر (سهامی خاص)',
    trade_name: 'فناوری نوین سپهر',
    short_name: 'سپهر تک',
    national_id: '10103456789',
    registration_number: '482910',
    legal_type: 'سهامی خاص',
    establishment_date: '1394/05/12',
    economic_code: '411589432198',
    workshop_code: '0289145620',
    business_scope: 'توسعه سامانه‌های کلان نرم‌افزاری، هوش مصنوعی و امنیت سایبری',
    phone: '021-88997766',
    mobile: '09121112233',
    official_email: 'info@sepehr-tech.ir',
    website: 'https://sepehr-tech.ir',
    head_office_address: 'تهران، خیابان ولیعصر، بالاتر از میدان ونک، برج فناوری سپهر، طبقه ۸',
    postal_code: '1969714321',
    ceo_name: 'مهندس سارا رادمنش',
    chairman_name: 'دکتر اصغر بهرامی',
    legal_representative: 'آقای علیرضا کاظمی',
    brand_color: '#2563eb', // Blue
    logo_url: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=120&auto=format&fit=crop&q=80',
    stamp_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=120&auto=format&fit=crop&q=80',
    letterhead_url: 'header_sepehr.png',
    subscription_start_at: '1404/01/01',
    subscription_end_at: '1406/01/01',
    status: 'active',
    description: 'شرکت اصلی هلدینگ متمرکز بر سامانه‌های ابری و امنیت',
    created_at: '1404/01/01 08:00',
    updated_at: '1405/01/01 10:00',
  },
  {
    id: 'comp_khavarmianeh',
    legal_name: 'گروه سرمایه‌گذاری و تجارت بین‌الملل خاورمیانه (سهامی عام)',
    trade_name: 'هلدینگ خاورمیانه',
    short_name: 'تجارت شرق',
    national_id: '10109876543',
    registration_number: '390124',
    legal_type: 'سهامی عام',
    establishment_date: '1388/11/20',
    economic_code: '411998877665',
    workshop_code: '0198765432',
    business_scope: 'سرمایه‌گذاری در زنجیره تأمین، صادرات، واردات و بازرگانی صنعتی',
    phone: '021-22334455',
    mobile: '09124445566',
    official_email: 'contact@mideast-invest.com',
    website: 'https://mideast-invest.com',
    head_office_address: 'تهران، سعادت‌آباد، بلوار شهرداری، مجتمع تجاری خاورمیانه، طبقه ۱۲',
    postal_code: '1998811223',
    ceo_name: 'دکتر محمدرضا صادقی',
    chairman_name: 'مهندس حمیدرضا کریمی',
    legal_representative: 'خانم بهاره شمس',
    brand_color: '#059669', // Emerald Green
    logo_url: 'https://images.unsplash.com/photo-1516876437184-593fda40c7ce?w=120&auto=format&fit=crop&q=80',
    stamp_url: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=120&auto=format&fit=crop&q=80',
    letterhead_url: 'header_khavarmianeh.png',
    subscription_start_at: '1403/06/01',
    subscription_end_at: '1406/06/01',
    status: 'active',
    description: 'شرکت هلدینگ با ۳۰ زیرمجموعه در بخش صنایع فلزی و بازرگانی',
    created_at: '1403/06/01 09:30',
    updated_at: '1404/12/28 14:15',
  },
  {
    id: 'comp_parspetro',
    legal_name: 'شرکت مهندسی و توسعه صنایع انرژی پارس پترو (سهامی خاص)',
    trade_name: 'پارس پترو',
    short_name: 'پتروپارس سازه',
    national_id: '10105554321',
    registration_number: '512039',
    legal_type: 'سهامی خاص',
    establishment_date: '1397/03/15',
    economic_code: '411223344556',
    workshop_code: '0345678901',
    business_scope: 'پیمانکاری عمومی EPC در پروژه‌های نفت، گاز و پتروشیمی',
    phone: '021-88771122',
    mobile: '09127778899',
    official_email: 'hq@parspetro-eng.ir',
    website: 'https://parspetro-eng.ir',
    head_office_address: 'تهران، خیابان پاسداران، نبش بهستان پنجم، پلاک ۴۴',
    postal_code: '1668833445',
    ceo_name: 'مهندس بهزاد توکلی',
    chairman_name: 'دکتر جمشید معتمدی',
    legal_representative: 'آقای فرهاد کیانی',
    brand_color: '#7c3aed', // Purple
    logo_url: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=120&auto=format&fit=crop&q=80',
    stamp_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=120&auto=format&fit=crop&q=80',
    letterhead_url: 'header_parspetro.png',
    subscription_start_at: '1404/01/01',
    subscription_end_at: '1405/12/29',
    status: 'active',
    description: 'شرکت تخصصی پروژه‌های زیربنایی و احداث مجتمع‌های پتروشیمی',
    created_at: '1404/01/01 11:00',
    updated_at: '1405/02/10 16:20',
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_admin',
    first_name: 'اصغر',
    last_name: 'بهرامی',
    father_name: 'حسین',
    national_id: '0078945612',
    birth_date: '1355/04/18',
    mobile: '09121112233',
    email: 'a.bahrami@sepehr-tech.ir',
    username: 'admin',
    profile_image_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80',
    is_active: true,
    last_login_at: '1405/07/06 09:12',
    created_at: '1404/01/01 08:00',
    updated_at: '1405/07/06 09:12',
  },
  {
    id: 'usr_radmanesh',
    first_name: 'سارا',
    last_name: 'رادمنش',
    father_name: 'منصور',
    national_id: '0065432198',
    birth_date: '1364/08/25',
    mobile: '09123334455',
    email: 's.radmanesh@sepehr-tech.ir',
    username: 's.radmanesh',
    profile_image_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
    is_active: true,
    last_login_at: '1405/07/06 08:45',
    created_at: '1404/01/01 08:30',
    updated_at: '1405/07/06 08:45',
  },
  {
    id: 'usr_secretary',
    first_name: 'فاطمه',
    last_name: 'محمدی',
    father_name: 'اکبر',
    national_id: '0451239874',
    birth_date: '1371/02/10',
    mobile: '09351234567',
    email: 'f.mohammadi@sepehr-tech.ir',
    username: 'secretary',
    profile_image_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80',
    is_active: true,
    last_login_at: '1405/07/06 07:55',
    created_at: '1404/01/05 09:00',
    updated_at: '1405/07/06 07:55',
  },
  {
    id: 'usr_financial',
    first_name: 'علیرضا',
    last_name: 'کاظمی',
    father_name: 'مرتضی',
    national_id: '0056781234',
    birth_date: '1360/11/04',
    mobile: '09127776655',
    email: 'a.kazemi@sepehr-tech.ir',
    username: 'finance_kazemi',
    profile_image_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80',
    is_active: true,
    last_login_at: '1405/07/05 16:30',
    created_at: '1404/01/05 09:00',
    updated_at: '1405/07/05 16:30',
  },
  {
    id: 'usr_archivist',
    first_name: 'مسعود',
    last_name: 'صابری',
    father_name: 'جواد',
    national_id: '0089123456',
    birth_date: '1366/06/14',
    mobile: '09198889900',
    email: 'm.saberi@sepehr-tech.ir',
    username: 'archivist_saberi',
    profile_image_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    is_active: true,
    last_login_at: '1405/07/06 08:10',
    created_at: '1404/01/10 10:00',
    updated_at: '1405/07/06 08:10',
  },
];

export const INITIAL_MEMBERSHIPS: CompanyMembership[] = [
  {
    id: 'mem_1',
    user_id: 'usr_admin',
    company_id: 'comp_sepehr',
    organizational_unit: 'ریاست هیئت مدیره و مدیریت عالی',
    position_title: 'رئیس هیئت مدیره و راهبر ارشد',
    role: 'super_admin',
    access_start_at: '1404/01/01',
    access_end_at: '1410/01/01',
    is_active: true,
    is_default_company: true,
    signature_url: 'sig_bahrami.png',
    signature_valid_until: '1406/12/29',
    created_at: '1404/01/01 08:00',
  },
  {
    id: 'mem_2',
    user_id: 'usr_admin',
    company_id: 'comp_khavarmianeh',
    organizational_unit: 'هیئت نظارت و بازرسی',
    position_title: 'عضو ارشد هیئت مدیره',
    role: 'board_member',
    access_start_at: '1404/01/01',
    access_end_at: '1410/01/01',
    is_active: true,
    is_default_company: false,
    signature_url: 'sig_bahrami.png',
    created_at: '1404/01/01 08:00',
  },
  {
    id: 'mem_3',
    user_id: 'usr_admin',
    company_id: 'comp_parspetro',
    organizational_unit: 'کمیته راهبری فنی',
    position_title: 'مشاور عالی هیئت مدیره',
    role: 'board_member',
    access_start_at: '1404/01/01',
    access_end_at: '1410/01/01',
    is_active: true,
    is_default_company: false,
    signature_url: 'sig_bahrami.png',
    created_at: '1404/01/01 08:00',
  },
  {
    id: 'mem_4',
    user_id: 'usr_radmanesh',
    company_id: 'comp_sepehr',
    organizational_unit: 'مدیریت عامل',
    position_title: 'مدیرعامل',
    role: 'company_admin',
    access_start_at: '1404/01/01',
    access_end_at: '1408/01/01',
    is_active: true,
    is_default_company: true,
    signature_url: 'sig_radmanesh.png',
    created_at: '1404/01/01 08:30',
  },
  {
    id: 'mem_5',
    user_id: 'usr_secretary',
    company_id: 'comp_sepehr',
    organizational_unit: 'دبیرخانه مرکزی',
    position_title: 'مسئول دبیرخانه و بایگانی جاری',
    role: 'secretary',
    access_start_at: '1404/01/05',
    access_end_at: '1407/01/01',
    is_active: true,
    is_default_company: true,
    created_at: '1404/01/05 09:00',
  },
  {
    id: 'mem_6',
    user_id: 'usr_financial',
    company_id: 'comp_sepehr',
    organizational_unit: 'مدیریت امور مالی و اداری',
    position_title: 'مدیر امور مالی و خزانه‌دار',
    role: 'financial_manager',
    access_start_at: '1404/01/05',
    access_end_at: '1408/01/01',
    is_active: true,
    is_default_company: true,
    created_at: '1404/01/05 09:00',
  },
  {
    id: 'mem_7',
    user_id: 'usr_archivist',
    company_id: 'comp_sepehr',
    organizational_unit: 'مرکز اسناد و بایگانی',
    position_title: 'مسئول بایگانی الکترونیک و راکد',
    role: 'archivist',
    access_start_at: '1404/01/10',
    access_end_at: '1408/01/01',
    is_active: true,
    is_default_company: true,
    created_at: '1404/01/10 10:00',
  },
];

export const INITIAL_LETTERS: Letter[] = [
  // Letters for Company Sepehr
  {
    id: 'let_sep_101',
    company_id: 'comp_sepehr',
    letter_number: 'سپهر-۱۴۰۵-۱۰۴۲',
    secretariat_registration_number: 'د-۴۰۵-۸۸۲۱',
    letter_type: 'اداری',
    direction: 'outgoing',
    subject: 'ارسال پیش‌نویس قرارداد فاز دوم مهاجرت ابری و زیرساخت امن',
    body: 'احتراماً پیرو مذاکرات صورت‌پذیرفته در خصوص اجرای فاز دوم پروژه سامانه‌های یکپارچه و بهینه‌سازی معماری چندمستاجری ابری، بدین‌وسیله نسخه نهایی قرارداد به انضمام پیوست فنی و زمان‌بندی تحویل اقلام حضورتان ارسال می‌گردد. خواهشمند است پس از بررسی دستور امضا و بازگرداندن نسخه دوم را صادر فرمایید.',
    letter_date: '۱۴۰۵/۰۷/۰۲',
    letter_date_gregorian: '2026-09-23',
    sent_date: '۱۴۰۵/۰۷/۰۲ 11:30',
    sender_name: 'مهندس سارا رادمنش (مدیرعامل فناوری نوین سپهر)',
    receiver_name: 'جناب آقای دکتر شمس‌الدین - معاونت فناوری اطلاعات و تحول دیجیتال',
    cc_recipients: ['مدیریت محترم مالی و قراردادها', 'واحد تضمین کیفیت نرم‌افزار'],
    responsible_user_name: 'مهندس سارا رادمنش',
    organizational_unit: 'مدیریت عامل',
    priority: 'instant',
    response_deadline: '۱۴۰۵/۰۷/۱۵',
    response_status: 'pending',
    confidentiality_level: 'confidential',
    keywords: ['قرارداد', 'رایانش ابری', 'فاز دوم', 'امنیت'],
    description: 'نامه رسمی ارسالی پیرامون قرارداد فاز ۲ با مهر برجسته شرکت',
    status: 'signed',
    qr_code_token: 'QR_TOK_SEP_99812A_SECURE_VERIFIED',
    signed_by_user_id: 'usr_radmanesh',
    signed_by_user_name: 'مهندس سارا رادمنش',
    signed_at: '۱۴۰۵/۰۷/۰۲ 11:15',
    signature_hash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    document_hash: 'a1b2c3d4e5f60718293a4b5c6d7e8f90123456789abcdef0123456789abcdef0',
    is_locked: true,
    locked_at: '۱۴۰۵/۰۷/۰۲ 11:15',
    revision_number: 1,
    created_by: 'خانم فاطمه محمدی (دبیرخانه)',
    created_at: '۱۴۰۵/۰۷/۰۲ 10:00',
    updated_at: '۱۴۰۵/۰۷/۰۲ 11:15',
    attachments_count: 2,
  },
  {
    id: 'let_sep_102',
    company_id: 'comp_sepehr',
    letter_number: 'سپهر-۱۴۰۵-۱۰۴۳',
    secretariat_registration_number: 'د-۴۰۵-۸۸۳۰',
    letter_type: 'مالی',
    direction: 'incoming',
    subject: 'اعلام واریز پیش‌پرداخت ارزی پروژه توسعه نرم‌افزار همراه سازمانی',
    body: 'با سلام، به اطلاع می‌رساند مبلغ ۷۵۰,۰۰۰,۰۰۰ ریال بابت پیش‌پرداخت قرارداد شماره پ-۹۰ به حساب بانک ملت شرکت فناوری نوین سپهر واریز گردید. تصویر رسید حواله بانکی به عنوان ضمیمه ارسال گردید.',
    letter_date: '۱۴۰۵/۰۷/۰۴',
    letter_date_gregorian: '2026-09-25',
    received_date: '۱۴۰۵/۰۷/۰۴ 14:00',
    sender_name: 'شرکت سرمایه‌گذاری کیان پارت (مهندس اخوان)',
    receiver_name: 'مدیریت امور مالی و حسابداری شرکت سپهر',
    cc_recipients: ['دبیرخانه مرکزی', 'مدیر پروژه نرم‌افزار'],
    responsible_user_name: 'آقای علیرضا کاظمی (مدیر مالی)',
    organizational_unit: 'امور مالی',
    priority: 'normal',
    response_deadline: '۱۴۰۵/۰۷/۱۰',
    response_status: 'answered',
    confidentiality_level: 'normal',
    keywords: ['پیش‌پرداخت', 'امور مالی', 'رسید بانکی'],
    status: 'delivered',
    qr_code_token: 'QR_TOK_SEP_99813B_SECURE_VERIFIED',
    is_locked: false,
    revision_number: 1,
    created_by: 'فاطمه محمدی',
    created_at: '۱۴۰۵/۰۷/۰۴ 14:05',
    updated_at: '۱۴۰۵/۰۷/۰۵ 09:20',
    attachments_count: 1,
  },
  {
    id: 'let_sep_103',
    company_id: 'comp_sepehr',
    letter_number: 'سپهر-۱۴۰۵-۱۰۴۴',
    secretariat_registration_number: 'د-۴۰۵-۸۸۳۵',
    letter_type: 'داخلی',
    direction: 'internal',
    subject: 'دستورالعمل رعایت الزامات امنیتی چندمستاجری و تفکیک داده‌ها در پروژه‌ها',
    body: 'کلیه تیم‌های فنی و مهندسی نرم‌افزار موظفند استانداردهای Tenant Isolation را در لایه‌های UI، API و Database با استفاده از شناسه شرکت فعال و فیلترهای Row-Level پیاده‌سازی نمایند. عدم تفکیک دقیق تخلف امنیتی درجه یک محسوب می‌شود.',
    letter_date: '۱۴۰۵/۰۷/۰۵',
    letter_date_gregorian: '2026-09-26',
    sender_name: 'دکتر اصغر بهرامی (رئیس هیئت مدیره)',
    receiver_name: 'کلیه مدیران واحدها و سرپرستان تیم‌های توسعه',
    cc_recipients: ['واحد امنیت اطلاعات', 'مدیریت حراست سازمانی'],
    responsible_user_name: 'دکتر اصغر بهرامی',
    organizational_unit: 'هیئت مدیره',
    priority: 'critical',
    response_status: 'none',
    confidentiality_level: 'secret',
    keywords: ['امنیت', 'چندمستاجری', 'دستورالعمل', 'Tenant Isolation'],
    status: 'signed',
    qr_code_token: 'QR_TOK_SEP_99814C_SECURE_VERIFIED',
    signed_by_user_id: 'usr_admin',
    signed_by_user_name: 'دکتر اصغر بهرامی',
    signed_at: '۱۴۰۵/۰۷/۰۵ 16:40',
    signature_hash: 'ffeeddccbbaa99887766554433221100aabbccddeeff00112233445566778899',
    document_hash: '99887766554433221100aabbccddeeff00112233445566778899aabbccddeeff',
    is_locked: true,
    locked_at: '۱۴۰۵/۰۷/۰۵ 16:40',
    revision_number: 1,
    created_by: 'اصغر بهرامی',
    created_at: '۱۴۰۵/۰۷/۰۵ 16:00',
    updated_at: '۱۴۰۵/۰۷/۰۵ 16:40',
    attachments_count: 0,
  },

  // Letters for Company Khavarmianeh (Company B - completely isolated!)
  {
    id: 'let_kha_201',
    company_id: 'comp_khavarmianeh',
    letter_number: 'خاور-۱۴۰۵-۰۲۱۵',
    secretariat_registration_number: 'ک-۴۰۵-۱۲۹۰',
    letter_type: 'بازرگانی',
    direction: 'outgoing',
    subject: 'استعلام بهای خرید شمش آلومینیوم و ورق‌های آلیاژی صنعتی',
    body: 'احتراماً خواهشمند است نرخ پیشنهادی خرید ۵۰۰ تن شمش آلومینیوم خلوص ۹۹.۷ درصد تحویل کارخانه را به انضمام شرایط تسویه و اعتبار اسنادی ظرف ۴۸ ساعت آینده به این هلدینگ اعلام فرمایید.',
    letter_date: '۱۴۰۵/۰۷/۰۱',
    letter_date_gregorian: '2026-09-22',
    sender_name: 'دکتر محمدرضا صادقی (مدیرعامل هلدینگ خاورمیانه)',
    receiver_name: 'مدیریت محترم فروش مجتمع آلومینیوم جنوب',
    cc_recipients: ['معاونت زنجیره تأمین', 'حراست بازرگانی'],
    responsible_user_name: 'دکتر محمدرضا صادقی',
    organizational_unit: 'معاونت بازرگانی',
    priority: 'instant',
    response_deadline: '۱۴۰۵/۰۷/۰۴',
    response_status: 'answered',
    confidentiality_level: 'confidential',
    keywords: ['خرید صنعتی', 'شمش آلومینیوم', 'استعلام بها'],
    status: 'signed',
    qr_code_token: 'QR_TOK_KHA_11223A_SECURE_VERIFIED',
    signed_by_user_id: 'usr_admin',
    signed_by_user_name: 'دکتر اصغر بهرامی (عضو هیئت مدیره)',
    signed_at: '۱۴۰۵/۰۷/۰۱ 14:10',
    is_locked: true,
    locked_at: '۱۴۰۵/۰۷/۰۱ 14:10',
    revision_number: 1,
    created_by: 'دبیرخانه خاورمیانه',
    created_at: '۱۴۰۵/۰۷/۰۱ 12:00',
    updated_at: '۱۴۰۵/۰۷/۰۱ 14:10',
    attachments_count: 1,
  },

  // Letters for Company Pars Petro (Company C - completely isolated!)
  {
    id: 'let_pet_301',
    company_id: 'comp_parspetro',
    letter_number: 'پترو-۱۴۰۵-۵۰۱۲',
    secretariat_registration_number: 'پ-۴۰۵-۳۳۸۱',
    letter_type: 'فنی مهندسی',
    direction: 'internal',
    subject: 'گزارش پیشرفت عملیات سیویل و پایپینگ فاز ۱۳ پتروشیمی عسلویه',
    body: 'عملیات جوشکاری خطوط لوله خوراک و نصب برج‌های تقطیر به پیشرفت فیزیکی ۷۸.۴ درصد رسیده است. مقتضی است برنامه زمان‌بندی تأمین شیرآلات کنترلی جهت جلوگیری از تاخیرات بحرانی ابلاغ گردد.',
    letter_date: '۱۴۰۵/۰۶/۲۸',
    letter_date_gregorian: '2026-09-19',
    sender_name: 'مهندس بهزاد توکلی (مدیرعامل پارس پترو)',
    receiver_name: 'مدیریت کارگاه و سرپرست نظارت عالیه عسلویه',
    cc_recipients: ['معاونت طرح و برنامه'],
    responsible_user_name: 'مهندس بهزاد توکلی',
    organizational_unit: 'معاونت مهندسی و پروژه‌ها',
    priority: 'normal',
    response_status: 'none',
    confidentiality_level: 'secret',
    keywords: ['پتروشیمی', 'سیویل', 'پایپینگ', 'عسلویه'],
    status: 'signed',
    qr_code_token: 'QR_TOK_PET_55667A_SECURE_VERIFIED',
    is_locked: true,
    locked_at: '۱۴۰۵/۰۶/۲۸ 17:00',
    revision_number: 1,
    created_by: 'بهزاد توکلی',
    created_at: '۱۴۰۵/۰۶/۲۸ 15:30',
    updated_at: '۱۴۰۵/۰۶/۲۸ 17:00',
    attachments_count: 3,
  },
];

export const INITIAL_ATTACHMENTS: Attachment[] = [
  {
    id: 'att_sep_01',
    company_id: 'comp_sepehr',
    module_name: 'secretariat',
    parent_record_type: 'letter',
    parent_record_id: 'let_sep_101',
    display_name: 'پیش‌نویس_قرارداد_فاز۲_رایانش_ابری.pdf',
    storage_name: 'f47ac10b-58cc-4372-a567-0e02b2c3d479.pdf',
    storage_path: 'tenant/comp_sepehr/secretariat/let_sep_101/f47ac10b-58cc-4372-a567-0e02b2c3d479.pdf',
    extension: 'pdf',
    mime_type: 'application/pdf',
    actual_mime_type: 'application/pdf',
    file_size: 2458000, // ~2.4 MB
    version: 1,
    uploaded_by: 'فاطمه محمدی',
    uploaded_at: '۱۴۰۵/۰۷/۰۲ 10:15',
    description: 'نسخه نهایی ویرایش شده قرارداد با مهر حقوقی',
    confidentiality_level: 'confidential',
    malware_scan_status: 'clean',
    approval_status: 'approved',
    sha256_hash: '2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae',
    is_deleted: false,
  },
  {
    id: 'att_sep_02',
    company_id: 'comp_sepehr',
    module_name: 'secretariat',
    parent_record_type: 'letter',
    parent_record_id: 'let_sep_101',
    display_name: 'جدول_زمان‌بندی_تحویل_اقلام_فنی.xlsx',
    storage_name: 'c9b3e10a-31df-4b92-8761-1a02c3d4e5f6.xlsx',
    storage_path: 'tenant/comp_sepehr/secretariat/let_sep_101/c9b3e10a-31df-4b92-8761-1a02c3d4e5f6.xlsx',
    extension: 'xlsx',
    mime_type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    actual_mime_type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    file_size: 489000,
    version: 1,
    uploaded_by: 'فاطمه محمدی',
    uploaded_at: '۱۴۰۵/۰۷/۰۲ 10:20',
    description: 'فایل اکسل مایلستون‌ها و زمان‌بندی تست‌های نفوذ',
    confidentiality_level: 'confidential',
    malware_scan_status: 'clean',
    approval_status: 'approved',
    sha256_hash: 'fcde2b2edba56bf408601fb721fe9b5c338d10ee429ea04fae5511b68fbf8fb9',
    is_deleted: false,
  },
  {
    id: 'att_sep_03',
    company_id: 'comp_sepehr',
    module_name: 'secretariat',
    parent_record_type: 'letter',
    parent_record_id: 'let_sep_102',
    display_name: 'رسید_حواله_ساتنا_بانک_ملت.png',
    storage_name: '7e2b109f-12aa-4890-bc45-998877665544.png',
    storage_path: 'tenant/comp_sepehr/secretariat/let_sep_102/7e2b109f-12aa-4890-bc45-998877665544.png',
    extension: 'png',
    mime_type: 'image/png',
    actual_mime_type: 'image/png',
    file_size: 780000,
    version: 1,
    uploaded_by: 'فاطمه محمدی',
    uploaded_at: '۱۴۰۵/۰۷/۰۴ 14:10',
    confidentiality_level: 'normal',
    malware_scan_status: 'clean',
    approval_status: 'approved',
    sha256_hash: 'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad',
    is_deleted: false,
  },
  {
    id: 'att_kha_01',
    company_id: 'comp_khavarmianeh',
    module_name: 'secretariat',
    parent_record_type: 'letter',
    parent_record_id: 'let_kha_201',
    display_name: 'مشخصات_فنی_شمش_آلومینیوم_صنعتی.pdf',
    storage_name: '6a11bb22-3344-5566-7788-99aabbccdde0.pdf',
    storage_path: 'tenant/comp_khavarmianeh/secretariat/let_kha_201/6a11bb22-3344-5566-7788-99aabbccdde0.pdf',
    extension: 'pdf',
    mime_type: 'application/pdf',
    actual_mime_type: 'application/pdf',
    file_size: 1540000,
    version: 1,
    uploaded_by: 'دبیرخانه خاورمیانه',
    uploaded_at: '۱۴۰۵/۰۷/۰۱ 12:30',
    confidentiality_level: 'confidential',
    malware_scan_status: 'clean',
    approval_status: 'approved',
    sha256_hash: '1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef',
    is_deleted: false,
  },
];

export const INITIAL_ARCHIVE_DOCUMENTS: ArchiveDocument[] = [
  {
    id: 'arc_sep_01',
    company_id: 'comp_sepehr',
    archive_code: 'بایگانی-س-۱۴۰۴-۰۳۲',
    case_folder_number: 'پرونده ۹۹/فنی/ابری',
    title: 'سند معماری زیرساخت داده‌های چندشرکتی و کلیدهای رمزنگاری',
    subject: 'معماری جامع تفکیک Tenantها، کلیدهای AES-256 در Keystore و جداول تفکیک‌شده',
    document_type: 'technical',
    document_date: '۱۴۰۴/۱۱/۲۰',
    sender_or_issuer: 'معماری نرم‌افزار سازمانی سپهر',
    receiver: 'تیم امنیت و استقرار DevOps',
    organizational_unit: 'معماری و امنیت',
    responsible_person: 'مسعود صابری (بایگان ارشد)',
    confidentiality_level: 'top_secret',
    retention_period_years: 15,
    status: 'locked',
    keywords: ['معماری', 'چندمستاجری', 'رمزنگاری', 'امنیت'],
    description: 'سند حیاتی الزامات ممیزی افتا و ایزو ۲۷۰۰۱ سامانه اتوماسیون',
    qr_code_token: 'QR_ARC_SEP_001_VERIFIED',
    version: 2,
    storage_path: 'tenant/comp_sepehr/archive/arc_sep_01/f47ac10b.pdf',
    file_name: 'Enterprise_MultiTenant_Architecture_v2.pdf',
    file_size_kb: 4890,
    file_extension: 'pdf',
    sha256_hash: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
    ocr_extracted_text: 'معماری جامع تفکیک شرکت‌ها بر اساس company_id، بررسی سطح دسترسی RBAC در لایه Repository و ذخیره‌سازی داده‌های آفلاین در پایگاه داده رمزنگاری‌شده Room با کلیدهای امن SQLCipher.',
    is_locked: true,
    created_at: '۱۴۰۴/۱۱/۲۰ 14:00',
    updated_at: '۱۴۰۵/۰۲/۱۵ 10:30',
  },
  {
    id: 'arc_sep_02',
    company_id: 'comp_sepehr',
    archive_code: 'بایگانی-س-۱۴۰۵-۰۱۴',
    case_folder_number: 'پرونده مالی/مالیات/۱۴۰۴',
    title: 'برگه قطعی مالیات بر عملکرد سال مالی ۱۴۰۳ شرکت سپهر',
    subject: 'مفاصاحساب مالیاتی صادره از سازمان امور مالیاتی کل کشور',
    document_type: 'financial',
    document_date: '۱۴۰۵/۰۴/۱۸',
    sender_or_issuer: 'سازمان امور مالیاتی شهر تهران',
    receiver: 'مدیریت مالی شرکت فناوری نوین سپهر',
    organizational_unit: 'امور مالی و حقوقی',
    responsible_person: 'علیرضا کاظمی',
    confidentiality_level: 'confidential',
    retention_period_years: 10,
    status: 'active',
    keywords: ['مالیات', 'مفاصاحساب', 'سال ۱۴۰۳'],
    description: 'تسویه کامل بدهی‌های مالیاتی عملکرد و ارزش افزوده',
    qr_code_token: 'QR_ARC_SEP_002_VERIFIED',
    version: 1,
    storage_path: 'tenant/comp_sepehr/archive/arc_sep_02/tax_clearance_1403.pdf',
    file_name: 'tax_clearance_1403.pdf',
    file_size_kb: 1240,
    file_extension: 'pdf',
    sha256_hash: '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8',
    is_locked: false,
    created_at: '۱۴۰۵/۰۴/۱۹ 11:20',
    updated_at: '۱۴۰۵/۰۴/۱۹ 11:20',
  },
  {
    id: 'arc_kha_01',
    company_id: 'comp_khavarmianeh',
    archive_code: 'بایگانی-خ-۱۴۰۵-۰۸۸',
    case_folder_number: 'پرونده گمرک و صادرات/شمش',
    title: 'پروانه ترخیص گمرکی محموله شمش روی و مس کاتد',
    subject: 'برگه سبز گمرک شهید رجایی بندرعباس جهت صادرات',
    document_type: 'administrative',
    document_date: '۱۴۰۵/۰۵/۱۰',
    sender_or_issuer: 'گمرک جمهوری اسلامی ایران',
    receiver: 'واحد صادرات هلدینگ خاورمیانه',
    organizational_unit: 'صادرات و واردات',
    responsible_person: 'بهاره شمس',
    confidentiality_level: 'confidential',
    retention_period_years: 7,
    status: 'active',
    keywords: ['گمرک', 'صادرات', 'شهید رجایی'],
    description: 'پروانه خروج کالا و تسویه تعهدات ارزی بانک مرکزی',
    qr_code_token: 'QR_ARC_KHA_001_VERIFIED',
    version: 1,
    storage_path: 'tenant/comp_khavarmianeh/archive/arc_kha_01/customs_slip.pdf',
    file_name: 'customs_slip_rajayi.pdf',
    file_size_kb: 3100,
    file_extension: 'pdf',
    sha256_hash: '4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a',
    is_locked: true,
    created_at: '۱۴۰۵/۰۵/۱۲ 13:40',
    updated_at: '۱۴۰۵/۰۵/۱۲ 13:40',
  },
];

export const INITIAL_FINANCIAL_TRANSACTIONS: FinancialTransaction[] = [
  {
    id: 'fin_sep_01',
    company_id: 'comp_sepehr',
    voucher_number: 'سند-سپهر-۴۰۵-۰۰۸۹',
    type: 'income',
    title: 'دریافت صورت‌حساب فاز اول پروژه توسعه نرم‌افزار سازمانی',
    amount: 14500000000, // 1.45 Billion Tomans
    transaction_date: '۱۴۰۵/۰۷/۰۱',
    payer_or_payee: 'شرکت پتروشیمی زاگرس',
    bank_account: 'حساب جاری بانک ملت - شعبه ونک (کد: ۸۹۱۰-۴۴۲-۹۹)',
    check_number: 'چک صیادی ۴۵۹۲۱۰۱۸',
    cost_center: 'مرکز درآمد پروژه‌های نرم‌افزاری',
    status: 'approved',
    approved_by: 'علیرضا کاظمی',
    description: 'تسویه نهایی صورت‌وضعیت شماره ۳ با اعمال کسورات قانونی بیمه و حسن انجام کار',
    attachments_count: 2,
    created_at: '۱۴۰۵/۰۷/۰۱ 10:30',
  },
  {
    id: 'fin_sep_02',
    company_id: 'comp_sepehr',
    voucher_number: 'سند-سپهر-۴۰۵-۰۰۹۰',
    type: 'expense',
    title: 'تمدید اجاره سرورهای ابری اختصاصی و لایسنس‌های امنیت شبکه',
    amount: 890000000, // 89 Million Tomans
    transaction_date: '۱۴۰۵/۰۷/۰۳',
    payer_or_payee: 'شرکت فناوری‌های ابری تبیان پارس',
    bank_account: 'حساب بانک تجارت - کد ۳۳۴',
    cost_center: 'مرکز هزینه فناوری اطلاعات و شبکه',
    status: 'settled',
    approved_by: 'سارا رادمنش',
    description: 'پرداخت فاکتور ماهانه کلاستر Kubernetes و فایروال‌های WAF اختصاصی',
    attachments_count: 1,
    created_at: '۱۴۰۵/۰۷/۰۳ 14:00',
  },
  {
    id: 'fin_sep_03',
    company_id: 'comp_sepehr',
    voucher_number: 'سند-سپهر-۴۰۵-۰۰۹۱',
    type: 'payroll',
    title: 'حقوق و دستمزد ماه شهریور تیم‌های توسعه، پشتیبانی و ستاد',
    amount: 6800000000, // 680 Million Tomans
    transaction_date: '۱۴۰۵/۰۶/۳۱',
    payer_or_payee: 'پرسنل و مهندسان شرکت سپهر (۴۸ نفر)',
    bank_account: 'بانک ملت - حساب واریز گروهی',
    cost_center: 'هزینه‌های عمومی و پرسنلی',
    status: 'settled',
    approved_by: 'دکتر اصغر بهرامی',
    description: 'پرداخت حقوق ماهانه بر اساس فایل دیسکت بانکی و کسر مالیات حقوق و حق بیمه تأمین اجتماعی',
    attachments_count: 3,
    created_at: '۱۴۰۵/۰۶/۳۱ 18:00',
  },
  // Financial for Khavarmianeh
  {
    id: 'fin_kha_01',
    company_id: 'comp_khavarmianeh',
    voucher_number: 'سند-خاور-۴۰۵-۰۲۵۰',
    type: 'receipt',
    title: 'دریافت ثمن معامله صادراتی ۵۰۰۰ تن مقاطع فولادی',
    amount: 85000000000, // 8.5 Billion Tomans
    transaction_date: '۱۴۰۵/۰۶/۲۹',
    payer_or_payee: 'کنسرسیوم تجاری الخلیج',
    bank_account: 'حساب ارزی بانک ملی ایران',
    cost_center: 'درآمد بازرگانی خارجی',
    status: 'settled',
    approved_by: 'دکتر محمدرضا صادقی',
    description: 'وصول وجه ال‌سی و تسویه از طریق سامانه نیما',
    attachments_count: 2,
    created_at: '۱۴۰۵/۰۶/۲۹ 11:00',
  },
];

export const INITIAL_SHAREHOLDERS: Shareholder[] = [
  {
    id: 'sh_sep_01',
    company_id: 'comp_sepehr',
    shareholder_code: 'سهم-سپهر-۰۰۱',
    full_name: 'دکتر اصغر بهرامی',
    national_id: '0078945612',
    share_type: 'ordinary',
    shares_count: 450000,
    nominal_value_per_share: 10000,
    total_value: 4500000000,
    ownership_percentage: 45.0,
    purchase_date: '1394/05/12',
    sheba_number: 'IR450120000000001234567890',
    bank_name: 'بانک ملت',
    phone: '09121112233',
    has_digital_signature: true,
    status: 'active',
  },
  {
    id: 'sh_sep_02',
    company_id: 'comp_sepehr',
    shareholder_code: 'سهم-سپهر-۰۰۲',
    full_name: 'مهندس سارا رادمنش',
    national_id: '0065432198',
    share_type: 'ordinary',
    shares_count: 350000,
    nominal_value_per_share: 10000,
    total_value: 3500000000,
    ownership_percentage: 35.0,
    purchase_date: '1394/05/12',
    sheba_number: 'IR120170000000009876543210',
    bank_name: 'بانک ملی',
    phone: '09123334455',
    has_digital_signature: true,
    status: 'active',
  },
  {
    id: 'sh_sep_03',
    company_id: 'comp_sepehr',
    shareholder_code: 'سهم-سپهر-۰۰۳',
    full_name: 'شرکت سرمایه‌گذاری آینده‌نگر پارس',
    national_id: '10108877665',
    share_type: 'preferred',
    shares_count: 200000,
    nominal_value_per_share: 10000,
    total_value: 2000000000,
    ownership_percentage: 20.0,
    purchase_date: '1399/08/10',
    sheba_number: 'IR890180000000004561237890',
    bank_name: 'بانک تجارت',
    phone: '021-88665544',
    has_digital_signature: false,
    status: 'active',
  },
  // Shareholders for Khavarmianeh
  {
    id: 'sh_kha_01',
    company_id: 'comp_khavarmianeh',
    shareholder_code: 'سهم-خاور-۱۰۱',
    full_name: 'دکتر محمدرضا صادقی',
    national_id: '0034567891',
    share_type: 'ordinary',
    shares_count: 15000000,
    nominal_value_per_share: 1000,
    total_value: 15000000000,
    ownership_percentage: 30.0,
    purchase_date: '1388/11/20',
    sheba_number: 'IR990150000000005566778899',
    bank_name: 'بانک پاسارگاد',
    phone: '09124445566',
    has_digital_signature: true,
    status: 'active',
  },
];

export const INITIAL_BOARD_MEETINGS: BoardMeeting[] = [
  {
    id: 'bm_sep_01',
    company_id: 'comp_sepehr',
    meeting_number: 'جلسه-سپهر-۱۴۰۵-۱۴',
    title: 'جلسه رسمی هیئت مدیره با دستور تصویب صورت‌های مالی و خط‌مشی امنیت چندشرکتی',
    scheduled_date: '۱۴۰۵/۰۶/۲۵',
    time: '۱۰:۰۰',
    venue: 'سالن کنفرانس سپهر - طبقه ۸ (با امکان اتصال رمزنگاری‌شده تصویری)',
    meeting_type: 'hybrid',
    interval_days: 15,
    suggested_next_meeting_date: '۱۴۰۵/۰۷/۱۰',
    status: 'minutes_signed',
    agenda_items: [
      'بررسی و استماع گزارش عملکرد سه‌ماهه دوم منتهی به شهریور ۱۴۰۵',
      'تصویب افزایش سرمایه شرکت از محل مطالبات حال‌شده و آورده نقدی',
      'تجهیز مرکز داده و استقرار استانداردهای ایزو ۲۷۰۰۱ برای داده‌های بین‌شرکتی',
      'تعیین پاداش و بودجه تحقیق و توسعه هوش مصنوعی',
    ],
    attendees: [
      {
        user_id: 'usr_admin',
        name: 'دکتر اصغر بهرامی',
        role: 'رئیس هیئت مدیره',
        is_present: true,
        has_signed: true,
        signature_time: '۱۴۰۵/۰۶/۲۵ 12:30',
      },
      {
        user_id: 'usr_radmanesh',
        name: 'مهندس سارا رادمنش',
        role: 'نایب رئیس و مدیرعامل',
        is_present: true,
        has_signed: true,
        signature_time: '۱۴۰۵/۰۶/۲۵ 12:35',
      },
      {
        user_id: 'usr_financial',
        name: 'آقای علیرضا کاظمی',
        role: 'منشی جلسه و مدیر مالی',
        is_present: true,
        has_signed: true,
        signature_time: '۱۴۰۵/۰۶/۲۵ 12:40',
      },
    ],
    decisions: [
      {
        id: 'dec_1',
        title: 'تصویب بودجه ۵۰ میلیارد ریالی ارتقای سرورهای اختصاصی',
        description: 'مقرر گردید واحد مالی با هماهنگی مدیریت فنی ظرف یک ماه نسبت به عقد قرارداد خرید سرور اقدام نماید.',
        responsible_person: 'علیرضا کاظمی (مدیر مالی)',
        due_date: '۱۴۰۵/۰۷/۲۵',
        status: 'in_progress',
      },
      {
        id: 'dec_2',
        title: 'برگزاری مجمع عمومی فوق‌العاده جهت افزایش سرمایه',
        description: 'آگهی دعوت در روزنامه کثیرالانتشار درج و هماهنگی با سازمان بورس به عمل آید.',
        responsible_person: 'سارا رادمنش (مدیرعامل)',
        due_date: '۱۴۰۵/۰۸/۱۰',
        status: 'pending',
      },
    ],
    minutes_text: 'جلسه با تلاوت آیاتی از کلام‌الله مجید در ساعت ۱۰ صبح به ریاست آقای دکتر اصغر بهرامی آغاز و تصمیمات فوق به اتفاق آرا به تصویب اعضای محترم رسید. جلسه در ساعت ۱۲:۳۰ خاتمه یافت.',
    minutes_signed_at: '۱۴۰۵/۰۶/۲۵ 12:40',
    is_locked: true,
    qr_code_token: 'QR_BM_SEP_1405_14_SIGNED_SECURE',
    created_at: '۱۴۰۵/۰۶/۲۵ 09:00',
  },
  {
    id: 'bm_sep_02',
    company_id: 'comp_sepehr',
    meeting_number: 'جلسه-سپهر-۱۴۰۵-۱۵',
    title: 'جلسه دوره‌ای ۱۵ روزه هیئت مدیره - پیگیری مصوبات و بررسی مناقصه جدید پتروشیمی',
    scheduled_date: '۱۴۰۵/۰۷/۱۰',
    time: '۱۴:۰۰',
    venue: 'سالن جلسات اصلی شرکت سپهر',
    meeting_type: 'in_person',
    interval_days: 15,
    suggested_next_meeting_date: '۱۴۰۵/۰۷/۲۵',
    status: 'scheduled',
    agenda_items: [
      'پیگیری وضعیت اجرای مصوبات جلسه چهاردهم',
      'بررسی ضمانت‌نامه شرکت در مناقصه اتوماسیون فرایندی پارس پترو',
      'بررسی درخواست استخدام ۸ مهندس ارشد DevOps و متخصص امنیت',
    ],
    attendees: [
      {
        user_id: 'usr_admin',
        name: 'دکتر اصغر بهرامی',
        role: 'رئیس هیئت مدیره',
        is_present: true,
        has_signed: false,
      },
      {
        user_id: 'usr_radmanesh',
        name: 'مهندس سارا رادمنش',
        role: 'مدیرعامل',
        is_present: true,
        has_signed: false,
      },
    ],
    decisions: [],
    is_locked: false,
    qr_code_token: 'QR_BM_SEP_1405_15_SCHEDULED',
    created_at: '۱۴۰۵/۰۶/۲۶ 11:00',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'prj_sep_01',
    company_id: 'comp_sepehr',
    code: 'PRJ-SEP-405-CLOUD',
    name: 'توسعه پلتفرم ابری اتوماسیون سازمانی و اپلیکیشن همراه اندروید',
    client_name: 'هلدینگ خاورمیانه و صنایع وابسته',
    location: 'تهران و کلیه شعب استانی',
    project_manager_name: 'مهندس پریسا رستگار',
    start_date: '۱۴۰۴/۰۸/۰۱',
    end_date: '۱۴۰۵/۱۰/۳۰',
    progress_percent: 74,
    budget: 38000000000,
    actual_cost: 26500000000,
    revenue: 35000000000,
    profitability_percent: 24.3,
    direct_employment_count: 32,
    indirect_employment_count: 65,
    job_types: ['معمار نرم‌افزار', 'توسعه‌دهنده Android', 'توسعه‌دهنده Backend', 'متخصص DevOps', 'تست‌کننده QA'],
    status: 'active',
    risks: [
      'نوسانات نرخ سخت‌افزار سرور و سوئیچ‌های شبکه',
      'تغییر نیازمندی‌های یکپارچه‌سازی با سامانه مودیان مالیاتی',
    ],
    is_joint_venture: true,
    joint_partners: [
      {
        company_id: 'comp_sepehr',
        company_name: 'فناوری نوین سپهر (طراحی و پیاده‌سازی)',
        share_percentage: 60,
        allocated_budget: 22800000000,
      },
      {
        company_id: 'comp_khavarmianeh',
        company_name: 'هلدینگ خاورمیانه (تأمین مالی و آزمون عملیاتی)',
        share_percentage: 40,
        allocated_budget: 15200000000,
      },
    ],
    created_at: '۱۴۰۴/۰۸/۰۱ 08:30',
  },
  {
    id: 'prj_sep_02',
    company_id: 'comp_sepehr',
    code: 'PRJ-SEP-405-SEC',
    name: 'پیاده‌سازی ماژول امضای دیجیتال، احراز هویت دوعاملی و ممیزی افتا',
    client_name: 'سازمان ملی استاندارد و تحول اداری',
    location: 'تهران',
    project_manager_name: 'مهندس حمید نیکزاد',
    start_date: '۱۴۰۵/۰۱/۱۵',
    end_date: '۱۴۰۵/۰۸/۳۰',
    progress_percent: 88,
    budget: 18000000000,
    actual_cost: 14200000000,
    revenue: 19500000000,
    profitability_percent: 27.1,
    direct_employment_count: 14,
    indirect_employment_count: 28,
    job_types: ['کارشناس امنیت سایبری', 'توسعه‌دهنده رمزنگاری', 'توسعه‌دهنده فرانت‌اند'],
    status: 'active',
    risks: ['تأخیر در دریافت گواهی ریشه مرکز صدور گواهی الکترونیکی کشور'],
    is_joint_venture: false,
    created_at: '۱۴۰۵/۰۱/۱۵ 09:00',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log_01',
    company_id: 'comp_sepehr',
    user_id: 'usr_radmanesh',
    user_name: 'مهندس سارا رادمنش',
    user_role: 'company_admin',
    module: 'secretariat',
    action: 'sign_letter',
    record_type: 'letter',
    record_id: 'let_sep_101',
    ip_address: '192.168.10.45',
    device_name: 'Samsung Galaxy Tab S9 (Android 14)',
    timestamp: '۱۴۰۵/۰۷/۰۲ 11:15',
    status: 'success',
    details: 'امضای الکترونیکی نامه شماره سپهر-۱۴۰۵-۱۰۴۲ با کلید رمزنگاری Keystore و قفل سند',
  },
  {
    id: 'log_02',
    company_id: 'comp_sepehr',
    user_id: 'usr_archivist',
    user_name: 'مسعود صابری',
    user_role: 'archivist',
    module: 'archive',
    action: 'view_document',
    record_type: 'document',
    record_id: 'arc_sep_01',
    ip_address: '192.168.10.112',
    device_name: 'Workstation Chrome (Ubuntu 24.04)',
    timestamp: '۱۴۰۵/۰۷/۰۶ 08:30',
    status: 'success',
    details: 'مشاهده سند محرمانه معماری چندمستاجری و اعتبارسنجی سطح دسترسی',
  },
  {
    id: 'log_03',
    company_id: 'comp_khavarmianeh',
    user_id: 'usr_unknown_threat',
    user_name: 'کاربر غیرمجاز (تلاش نفوذ)',
    user_role: 'guest',
    module: 'secretariat',
    action: 'cross_tenant_access_attempt',
    record_type: 'letter',
    record_id: 'let_kha_201',
    ip_address: '45.143.20.12',
    device_name: 'Automated Penetration Script / Python',
    timestamp: '۱۴۰۵/۰۷/۰۵ 03:14',
    status: 'forbidden_attempt',
    failure_reason: 'تلاش برای خواندن نامه هلدینگ خاورمیانه با توکن معتبر شرکت فناوری سپهر (Tenant Mismatch Blocked)',
    details: 'مسدودسازی خودکار درخواست با کد وضعیت 403 Forbidden و ارسال هشدار به مرکز عملیات امنیت (SOC)',
  },
  {
    id: 'log_04',
    company_id: 'comp_sepehr',
    user_id: 'usr_financial',
    user_name: 'علیرضا کاظمی',
    user_role: 'financial_manager',
    module: 'finance',
    action: 'approve_voucher',
    record_type: 'voucher',
    record_id: 'fin_sep_01',
    ip_address: '192.168.10.88',
    device_name: 'Windows Desktop Client',
    timestamp: '۱۴۰۵/۰۷/۰۱ 10:45',
    status: 'success',
    details: 'تأیید نهایی سند دریافت شماره سند-سپهر-۴۰۵-۰۰۸۹ به مبلغ ۱۴,۵۰۰,۰۰۰,۰۰۰ ریال',
  },
];

export const INITIAL_USER_DEVICES: UserDevice[] = [
  {
    id: 'dev_01',
    user_id: 'usr_admin',
    device_name: 'Samsung Galaxy S24 Ultra (Android 15)',
    platform: 'Android',
    device_identifier_hash: 'hash_a8f934bd01c798e',
    last_login_at: '۱۴۰۵/۰۷/۰۶ 09:12',
    last_seen_at: 'همین حالا',
    is_active: true,
    ip_address: '178.252.189.44',
    location: 'تهران، منطقه ۳',
  },
  {
    id: 'dev_02',
    user_id: 'usr_admin',
    device_name: 'Chrome on MacBook Pro (macOS Sequoia)',
    platform: 'Web_Chrome',
    device_identifier_hash: 'hash_b2c451da7890ef1',
    last_login_at: '۱۴۰۵/۰۷/۰۵ 18:20',
    last_seen_at: 'دیروز ۱۸:۲۰',
    is_active: true,
    ip_address: '192.168.10.1',
    location: 'دفتر مرکزی ونک',
  },
  {
    id: 'dev_03',
    user_id: 'usr_admin',
    device_name: 'Windows 11 Enterprise Workstation',
    platform: 'Windows_Desktop',
    device_identifier_hash: 'hash_c991823ab4567cd',
    last_login_at: '۱۴۰۵/۰۶/۲۹ 10:15',
    last_seen_at: '۶ روز پیش',
    is_active: false,
    ip_address: '192.168.10.22',
    location: 'اتاق جلسات هیئت مدیره',
  },
];

export const INITIAL_BACKUPS: BackupRecord[] = [
  {
    id: 'bak_01',
    company_id: 'comp_sepehr',
    scope: 'company',
    backup_type: 'full',
    file_name: 'backup_comp_sepehr_full_14050701_1800.enc.bak',
    file_size_mb: 284.5,
    created_at: '۱۴۰۵/۰۷/۰۱ ۱۸:۰۰',
    status: 'completed',
    checksum_sha256: '9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b',
    is_encrypted: true,
    notes: 'پشتیبان خودکار دوره‌ای ماهانه شامل پایگاه داده، ضمایم، لاگ‌ها و تنظیمات شرکت سپهر',
  },
  {
    id: 'bak_02',
    company_id: null,
    scope: 'system',
    backup_type: 'incremental',
    file_name: 'backup_system_all_tenants_incr_14050705_0200.enc.bak',
    file_size_mb: 840.2,
    created_at: '۱۴۰۵/۰۷/۰۵ ۰۲:۰۰',
    status: 'completed',
    checksum_sha256: '11223344556677889900aabbccddeeff00112233445566778899aabbccddeeff',
    is_encrypted: true,
    notes: 'پشتیبان افزایشی سامانه جامع شامل تمام مستاجران با رمزنگاری AES-256 و کلید مدیریت کل',
  },
];
